# Generated by Django 3.1.3 on 2023-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20231017_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'giáo viên'), ('student', 'người học')], default='student', max_length=10),
        ),
    ]
