# Generated by Django 3.1.3 on 2023-10-17 17:53

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_auto_20201012_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Notes',
            field=models.FileField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Số chương'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ppt',
            field=models.FileField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Bài giảng'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, upload_to=curriculum.models.save_subject_image, verbose_name='Ảnh môn học'),
        ),
    ]
