# Generated by Django 3.1.3 on 2023-11-24 10:02

import curriculum.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_auto_20231124_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, upload_to=curriculum.models.save_subject_image, verbose_name='Subject Image'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='curriculum.standard'),
        ),
    ]
